  // Boats named in a community vehicle summary (September 2026) with no record
  // here yet. Sightings are claimed from official media, but the model
  // identifications are the community's, so they are filed as analysis.
  V('bavaria-sr33-inspired-boat', 'BAVARIA SR33-INSPIRED BOAT', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'TRAILER 1 · COMMUNITY IDENTIFICATION', [], ['Reported as a compact recreational cruiser modelled on the Bavaria SR33.', 'In-game name, manufacturer and statistics.'], 'NOT OFFICIALLY SPECIFIED'),
  V('ferry', 'FERRY', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'AN EXTENDED LOOK · COMMUNITY IDENTIFICATION', [], ['Reported as a passenger and vehicle ferry modelled on the Elliott Bay Design Group ferries serving Miami’s Fisher Island.', 'Whether it can be driven, and its route.'], 'NOT OFFICIALLY SPECIFIED'),
  V('highfield-sport-900-inspired-boat', 'HIGHFIELD SPORT 900-INSPIRED BOAT', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'OFFICIAL SCREENSHOT · COMMUNITY IDENTIFICATION', [], ['Reported as a large rigid inflatable modelled on the Highfield Sport 900.', 'In-game name, manufacturer and statistics.'], 'NOT OFFICIALLY SPECIFIED'),
  V('rb-s-inspired-response-boat', 'RB-S-INSPIRED RESPONSE BOAT', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'OFFICIAL SCREENSHOT · COMMUNITY IDENTIFICATION', [], ['Reported as a fast response boat modelled on the first-generation Response Boat-Small used by maritime agencies; the second generation has its own record.', 'In-game name and operator.'], 'NOT OFFICIALLY SPECIFIED'),
  V('speeder', 'SPEEDER', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'TRAILER 1 · COMMUNITY IDENTIFICATION', [], ['Reported as the returning Pegassi Speeder from GTA V and GTA Online, drawing on the Coeur 290 Nighthawk and Cherubini Classic 20.', 'Rockstar confirmation of the name.'], 'PEGASSI'),
  V('tropic', 'TROPIC', 'boats', [0,0,0,0], ['—','—','—','—'], 'analysis', null, '000', null, null, ['Community summary', null], true, 'TRAILER 1 · COMMUNITY IDENTIFICATION', [], ['Reported as the returning Shitzu Tropic, a cabin cruiser modelled on the Sea Ray 300 Sundancer.', 'Rockstar confirmation of the name.'], 'SHITZU'),
