  // Muscle (community summary, September 2026)
  'vehicle:buccaneer': ['Reported weight about 1,600 kg.'],
  'vehicle:buffalo-stx': ['Reported weight about 1,800 kg, with eight gears.'],
  'vehicle:chino': ['Reported weight about 2,300 kg.'],
  'vehicle:deviant': ['Reported as based on the 1972 AMC Javelin and listed as part of the Wyman collection.'],
  'vehicle:dominator': ['Reported weight about 1,600 kg.'],
  'vehicle:dominator-1967': ['Reported as based on the first-generation Ford Mustang.'],
  'vehicle:dominator-asp': ['Reported weight about 1,665 kg.'],
  'vehicle:dominator-gt': ['Reported weight about 1,820 kg, with six gears.'],
  'vehicle:dominator-gtx': ['Reported weight about 1,670 kg.'],
  'vehicle:ganado': ['Reported as the 1970 Ganado, drawing on the Ford Ranchero and Mercury Cougar; linked to Jason and to a Retro Build variant.'],
  'vehicle:gauntlet-classic-custom': ['The summary also lists a stock Gauntlet Classic at about 1,350 kg; the archive has no separate record for it.'],
  'vehicle:gauntlet-hellfire': ['Reported weight about 1,940 kg.'],
  'vehicle:impaler-1980': ['Reported under the name Impaler ’80 (earlier listed as Impaler LX), weight about 1,630 kg.'],
  'vehicle:impaler-sz': ['Reported weight about 1,830 kg.'],
  'vehicle:moonbeam': ['Listed by the summary as a muscle car (the archive files it under vans), weight about 2,400 kg, from 2022 footage.'],
  'vehicle:phoenix': ['Reported weight about 1,700 kg.'],
  'vehicle:ruiner': ['Reported weight about 1,300 kg.'],
  'vehicle:sabre-turbo': ['Reported weight about 1,200 kg.'],
  'vehicle:sirius': ['Reported as based on the 1970 Mercury Cougar and listed as part of the Wyman collection.'],
  'vehicle:slamvan': ['Reported weight about 1,200 kg.'],
  'vehicle:tulip': ['Reported weight about 1,545 kg; linked to Jason.'],
  'vehicle:tulip-m-100': ['Reported weight about 1,400 kg, with three gears.'],
  'vehicle:vigero-zx-convertible': ['Reported weight about 1,890 kg.'],
