  // Off-Road (community summary, September 2026)
  'vehicle:bison-900-monster-truck': ['Reported as the Bravado Bison 900 ’95 Monster Truck, a new monster-truck take on a second-generation Dodge Ram pickup: four seats, oversized tyres and extreme ground clearance, from official screenshots. No statistics yet.'],
  'vehicle:blazer': ['Reported as the returning Nagasaki Blazer quad bike, based on the Yamaha YFZ450: one seat, about 600 kg, all-wheel drive, five gears; seen in Trailer 1. Earlier: GTA V, San Andreas and Vice City Stories.'],
  'vehicle:caracara-4x4': ['Reported as based on the second-generation Ford F-150 Raptor: four seats, about 2,480 kg, all-wheel drive, six gears; seen in Trailer 2. Brian Heder is named as an owner.'],
  'vehicle:dominator-buggy': ['The summary lists the Vapid Dominator ’67 Buggy as off-road: a lifted first-generation Mustang with oversized tyres, two seats, from the Ultimate Edition, storable at Paradise Garage in Watson Bay and possibly tied to the Mud Club.'],
  'vehicle:vapid-dominator-buggy-67': ['Reported as an Ultimate Edition vehicle storable at Paradise Garage in Watson Bay (with a weapon locker and stolen-goods storage), aimed at the Mount Kalaga backcountry and possibly tied to the Mud Club.'],
  'vehicle:hellion': ['Reported as the returning Annis Hellion, mixing the Nissan Patrol Safari Y60 and Jeep Cherokee XJ: two seats, about 1,900 kg, all-wheel drive, five gears; seen in Trailer 1.'],
  'vehicle:kamacho': ['Reported as the returning Canis Kamacho, based on the Jeep Crew Chief 715 concept: four seats, about 2,350 kg, all-wheel drive, five gears. Also shown in Ultimate Edition material tied to One-Eyed Willie’s customisation shop.'],
  'vehicle:outlaw': ['Reported as the returning Nagasaki Outlaw side-by-side, based on the Can-Am Maverick X3 Turbo: two seats, about 850 kg, all-wheel drive, three gears; seen in Trailer 1.'],
  'vehicle:rancher': ['Reported as the returning Declasse Rancher, based on older Chevrolet Suburban models: four seats, about 2,400 kg, all-wheel drive, five gears.'],
  'vehicle:rebel': ['Reported as the returning Karin Rebel, based on the Toyota Hilux: two seats, about 2,400 kg, all-wheel drive, five gears.'],
  'vehicle:reclaimer': ['Reported as a new Vapid midsize pickup based on the 2019–2023 Ford Ranger T6, with four seats; seen in Trailer 1. No other statistics yet.'],
  'vehicle:sandking-xl': ['Reported as the returning Vapid Sandking XL, based on Ford Super Duty trucks: four seats, about 2,400 kg, all-wheel drive, six gears; seen in Trailer 1.'],
  'vehicle:swamp-buggy': ['Reported as based on the Palm Beach swamp buggy, with very tall wheels and raised bodywork for mud, marsh and flooded ground, suited to the Grassrivers. Maker and statistics unknown.'],
  'vehicle:terminus': ['Reported as the returning Canis Terminus, based on the Jeep Wrangler Rubicon (JL): four seats, about 2,000 kg, all-wheel drive, six gears.'],
  'vehicle:verus': ['Reported as the returning Dinka Verus utility ATV, based on the Polaris Sportsman MV850 and 570: two seats, about 750 kg, all-wheel drive, five gears.'],
  'vehicle:walton-l35-stock': ['Reported as the Declasse Walton L35, based on the 1991–1993 Chevrolet S-10: two seats, about 1,600 kg, all-wheel drive, five gears; shown around Port Gellhorn.'],
  'vehicle:yosemite-1500': ['Reported as the returning Declasse Yosemite 1500, based on the first-generation Chevrolet Silverado: two seats, about 1,830 kg, all-wheel drive, four gears.'],
