// Details from community topic summaries supplied to the archive in September
// 2026 (features, characters, wildlife). They are kept apart from each
// record's sourced text and rendered under their own heading: a detail here is
// never promoted to the record's status or attributed to its source.

export const REPORTED_SOURCE = 'community summaries supplied to the archive in September 2026'

const REPORTED = {
  // ---- Characters ----
  'character:jason-duval': [
    'Described as the more cautious half of the pair, pulled toward bigger risks by his partnership with Lucia.',
    'Lives rent-free at one of Brian Heder’s properties in exchange for help with local shakedowns.',
    'Also called Jay. Reported vehicles: a Ganado ’70 and a Tulip; reported homes: the Key Lento safehouse and the Starlet Motel.',
  ],
  'character:lucia-caminos': [
    'Her mother is said to have dreamed of a better life since the family’s earlier years in Liberty City.',
    'Introduced wearing an electronic ankle monitor after her release from prison.',
    'Reported to have extra cosmetic options, including nail customisation.',
    'Her occupations are given as robber and car thief; she shares the Key Lento safehouse and the Starlet Motel with Jason.',
  ],
  'character:brian-heder': [
    'Runs his smuggling from a boat yard named in the summary as Brian’s Boat Works & Marina.',
    'Increasingly hands dangerous jobs to younger associates, Jason among them, including collecting from people who owe him.',
    'Reported vehicle: a Caracara 4x4.',
  ],
  'character:lori-heder': [
    'Brian Heder’s third wife; works alongside him at the boat yard.',
    'Seen handling both pistols and rifles.',
  ],
  'character:cal-hampton': [
    'Spends his time at home drinking beer, browsing the internet and listening to Coast Guard radio traffic.',
    'Drawn to conspiracy theories and suspicious of governments and institutions.',
  ],
  'character:boobie-ike': [
    'Business interests reported as real estate, a recording studio, other entertainment ventures and the Jack of Hearts, a Vice City strip club.',
    'Also linked to Raymond and Ernesto of San4San; the nature of that connection has not been explained.',
    'Partnered with Dre’Quan Priest on Only Raw Records.',
  ],
  'character:dre-quan-priest': [
    'Booked performers at Boobie Ike’s club before turning to Only Raw Records; also described as a hip-hop artist himself.',
    'Signed the rap duo Real Dimez to Only Raw Records.',
  ],
  'character:real-dimez': [
    'A duo of high-school friends, Bae-Luxe and Roxy, who drew on past street crime for their music and image.',
    'An early collaboration with local rapper DWNPLY gave them their first breakthrough.',
    'Their street past reportedly included robbing local drug dealers; after the breakthrough came several lean years before the Only Raw Records deal.',
  ],
  'character:bae-luxe': ['One half of Real Dimez; drives the duo’s social-media promotion.'],
  'character:roxy': ['The other half of Real Dimez, friends with Bae-Luxe since high school.'],
  'character:raul-bautista': ['A professional bank robber who recruits capable people for increasingly dangerous scores.'],
  'character:stefanie': [
    'The summary gives her full name as Stefanie Gates, a correctional social worker with the Leonida Department of Corrections.',
    'Meets Lucia at the Leonida Penitentiary and appears during her return to civilian life.',
    'Said to be the first voice heard in the first trailer, asking Lucia in a prison office how she ended up there.',
  ],
  'character:camilo': [
    'Spelled “Camillo” in the summary.',
    'A Vice City livestreamer filming a challenge from inside a car’s trunk when Lucia steals the car, his friend’s Buffalo. He keeps streaming from the open trunk through the police pursuit along Shore Drive.',
  ],
  'character:andres-de-leon': [
    'A Megamundo associate whom Jason and Lucia are hired to escort to the opening of the company’s first US headquarters.',
    'An armed crew attacks the opening and takes him hostage; Jason later rescues him.',
    'Portrayed as a wealthy socialite with a taste for recreational drugs, close to Petra Navarro in a way not yet explained.',
  ],
  'character:valentina': [
    'Hires Jason and Lucia for the Megamundo escort and introduces them to Petra Navarro; the event is interrupted by an armed robbery.',
    'Also called Val or Tina. She is said to have appeared briefly in GTA Online, which would tie her to the existing HD Universe.',
  ],
  'character:petra-navarro': ['Chief operating officer of Megamundo; meets Jason and Lucia at the headquarters opening and is closely associated with Andrés de León.'],
  'character:mendez': ['A Vice City Police Department officer who takes part in a raid on a drug deal involving Jason, Lucia and Raymond; the pair appear to know him and avoid being identified.'],
  'character:raymond': [
    'Also called Ray; described as Haitian-American. Runs a San4San drug house from the Venture Apartments in Rockridge and works in the same network as Ernesto.',
    'Also linked to Boobie Ike, in a way not yet explained.',
  ],
  'character:ernesto': ['Works with Raymond in a San4San drug-production operation, and is linked to Boobie Ike in a way not yet explained.'],
  'character:phil': [
    'Owns Phil’s Ammu-Nation and appears in its advertising; read by fans as a modern take on Phil Cassidy.',
    'He is younger and has both arms, while the 3D Universe Phil Cassidy loses one in GTA Vice City, so continuity between the two is unconfirmed.',
  ],
  'character:wyman': [
    'Runs Wyman’s World Auto Salvage Co. and commissions the search for abandoned classics and unfinished project cars.',
    'Gives the Classic Car Collection side mission, in which found parts are delivered to him and rebuilt into working cars.',
    'Reported to be based in Port Gellhorn.',
  ],
  'character:leonida-impertinent': ['The summary calls him the “Leonida Joker”. Neither that nor this record’s title is a Rockstar name.'],
  'character:hamlet-woman': ['The summary calls her the “Hammer Lady”. Neither that nor this record’s title is a Rockstar name.'],
  'character:rudi': ['Appears to be memorialised in a social-media post after a dangerous vehicle stunt.'],
  'character:shanese': ['Posts as @Shaneycee and interacts with content about a street takeover.'],
  'character:selfie-guy': ['Seen near Jason and Lucia more than once, around Vice City bars and parties.'],

  // ---- Mechanics ----
  'mechanic:character-switching': [
    'Switching can happen in free roam and inside missions, sometimes showing the same scene from each protagonist’s role.',
    'Both protagonists can share activities such as robberies, shopping, gym sessions and travel.',
  ],
  'mechanic:passenger-mode': ['One protagonist can drive while the other fires from the passenger seat.'],
  'mechanic:focus-ability': ['Jason is said to have a slow-motion aim that marks key targets and weak points; Lucia a precision-focused equivalent.'],
  'mechanic:personal-inventory': [
    'Characters carry fewer weapons than in GTA V, with the rest stored in vehicles.',
    'Carried equipment reportedly includes binoculars, flashlights, body armour, medical items, food, drinks, tools and bags; some of it can be shared between the protagonists.',
  ],
  'mechanic:vehicle-cargo': ['Vehicle menus reportedly manage weapons, equipment, cargo and components, encouraging players to kit out before a job.'],
  'mechanic:six-star-wanted': [
    'Police are said to identify suspects by clothing, appearance, vehicle, location and witness reports.',
    'Response times reportedly vary: isolated rural areas wait longer than central Vice City.',
    'Surrender is reported to be possible in some situations.',
  ],
  'mechanic:criminal-profile': ['Witnesses may call the police, and repeated violent or reckless behaviour is said to harden both civilian and police reactions.'],
  'mechanic:disguises': ['Changing clothes or switching vehicles is reported to lower the chance of being identified.'],
  'mechanic:contextual-interactions': [
    'Reported options include greeting, taunting, threatening, calming a situation and intimidating.',
    'Dogs can reportedly be petted, scolded or given treats bought in stores.',
  ],
  'mechanic:reactive-weapon-presence': ['Characters are said to lower or hide a weapon automatically in some situations, and crowds to react collectively to major incidents.'],
  'mechanic:physical-conditioning': [
    'Overeating is said to add weight and training to add muscle; poor sleep, heavy drinking and physical stress may also show.',
    'Food and drink reportedly restore health or give short boosts to stamina, workouts or energy.',
  ],
  'mechanic:dynamic-events': [
    'Events reportedly involve civilians, police, criminals, businesses, animals, accidents and robberies.',
    'Traffic and crowd density are said to change with location and time of day.',
    'A dynamic tropical weather system, including rain and storms, is reported to change the look of the state.',
    'Random events may count toward 100% completion; how many, if any, has not been revealed.',
  ],
  'mechanic:snapmatic': ['The phone’s social platforms are described as inspired by short-form video apps, with posts reflecting events in the world.'],
  'mechanic:public-transit': ['The summary names trams and a metro among the usable systems.'],
  'mechanic:safehouse-economy': [
    'Garages and properties can reportedly be bought for vehicle storage, weapon lockers, equipment and stolen goods.',
    'Homes are said not to be bought: new safehouses open up as the story moves Jason and Lucia on. Garages are acquired separately.',
    'Three homes are reported so far: the Key Lento stilt house (three vehicles), the Bayside apartment (one) and the Starlet Motel (one).',
    'Two garages are reported: Shore Court (Vintage Vice City Pack) and Paradise Garage (Ultimate Edition), both with a weapon locker, stolen-goods storage and fencing access.',
    'Whether commercial businesses can be owned has not been shown.',
  ],
  'mechanic:vehicle-fencing': ['Criminal contacts are said to sell stolen property and remove tracking devices from valuable vehicles.'],
  'mechanic:free-roam-pursuits': [
    'The summary also lists pool, boxing, mini-golf, fishing, hunting, racing and gym training.',
    'Most listed activities are said to count toward 100% completion and to stay available after the story ends.',
    'Also reported: car, bike and boat meets, dancing, drinking, nightclubs, strip clubs, arcade-style games, sunbathing and watching TV.',
    'Tennis courts exist in the world, but tennis is not reported as playable.',
  ],
  'mechanic:robberies': [
    'Convenience stores can reportedly be robbed outside story missions, with police and witnesses reacting.',
    'The same stores can be used normally to buy food, drinks and other consumables.',
  ],
  'mechanic:wildlife-checklist': ['Studying an animal is said to add its species to the checklist; a visitable zoo is also reported.', 'Whether completing the checklist counts toward 100% has not been confirmed.'],

  // ---- Properties ----
  'world:key-lento-safehouse': [
    'A green stilt house on the water in Key Lento, reported to hold three vehicles; Jason’s car is seen parked outside.',
    'Outside: a balcony, a raised living area, parking, stairs up to the house and a basketball hoop at their foot. Jason is seen repairing roof leaks; his Ganado ’70 is parked outside.',
    'Inside: a sofa, a television, a game console, chairs, a glass table and a snake enclosure.',
    'Lucia appears to move in with Jason after leaving prison.',
  ],
  'world:bayside-safehouse': [
    'An apartment in Bayside, Vice-Dale County, reported to hold one vehicle; Jason and Lucia are seen living there later in the story.',
    'It has a living room, kitchen, bedroom, bathroom and balcony. Footage shows the pair opening the fridge, taking drinks, watching TV, switching lights and resting on the bed.',
    'The complex is said to recreate a real development at 419 NE 4th Avenue in Miami, demolished around 2023.',
    'Its ownership is unclear, though it is most associated with Lucia; when it unlocks in the story has not been shown.',
  ],
  'world:shore-court-garage': ['Players with the Vintage Vice City Pack are said to have it from the start of the game.'],
  'location:starlet-motel': [
    'Reported as a temporary safehouse where Jason and Lucia share a room while moving through Port Gellhorn, Kelly County.',
    'Reported capacity: one vehicle.',
    'It appeared in the first reveal, in a scene between Jason and Lucia built around trust, and again in later Port Gellhorn promotional material.',
  ],
  'location:paradise-garage': [
    'Reported as an Ultimate Edition garage with a weapon locker, stolen-goods storage and fencing access, tied to the ’67 Vapid Dominator Buggy.',
    'The buggy is described as a lifted off-road take on a first-generation Ford Mustang. The garage’s vehicle capacity has not been given.',
  ],

  // ---- Activities ----
  'world:basketball': [
    'Courts around Leonida are said to host shooting challenges, score contests and one-on-one games; the Key Lento safehouse has its own hoop.',
    'Shots are reported to be aimed and timed by the player rather than animated, and making them to raise the Focus attribute.',
  ],
  'world:boxing-and-fighting': ['Fights are reported in underground gyms and informal spots, built on the expanded hand-to-hand combat, with money, reputation or stat rewards for wins.'],
  'world:kayaking': ['Paddle kayaks are said to reach quiet rivers, swamps, lakes and coastal inlets that larger boats cannot, including some remote collectibles.'],
  'world:mini-golf': ['Themed putting courses with obstacles, ramps and moving parts; scores are counted in strokes.'],
  'world:off-road-racing': ['Routes reportedly cross dirt roads, mountain trails and forest paths around Mount Kalaga, raced on ATVs, dirt bikes, buggies and trucks.'],
  'world:parachuting': ['Jumps from heights or aircraft through checkpoints to a landing target, with cash rewards scaled by accuracy.'],
  'world:pool': ['Tables in bars and venues; games such as 8-ball against NPCs.'],
  'world:scuba-diving': [
    'Dives reportedly reach reefs, shipwrecks, caves and submerged structures, with an oxygen meter, loot and objectives such as photographing marine animals.',
    'A Lung Capacity attribute is said to improve how long characters can stay under without gear.',
  ],
  'world:sea-racing': ['Boat and watercraft races across the coast, bays and rivers; formats, locations and rewards have not been detailed.'],
  'world:shooting-range': ['Challenges by weapon category with bronze, silver and gold medals; they are said to raise Shooting Skill, and bronze is reported as the bar for 100% completion.'],
  'world:street-racing': ['Checkpoint races, head-to-head races and time trials on streets and highways, by car or motorcycle, for cash and vehicle upgrades.'],
  'world:wrestling': ['Footage shows backyard wrestling in a makeshift ring, including a move resembling John Cena’s Attitude Adjustment. Whether it is a repeatable activity or part of a mission is not known.'],
  'world:wyman-s-classic-car-collection': [
    'Parts for abandoned classics are found around Leonida, often off the main roads, and delivered to Wyman’s World Auto Salvage Co. to be rebuilt.',
    'Vehicles reported for the collection: Deviant, Mamba GT, Riata Classic and Sirius.',
    'Reported as exclusive to the Ultimate Edition and counted toward 100% completion.',
  ],
  'world:television-in-gta-vi': ['Television can reportedly be watched inside safehouses and other interiors.'],

  // ---- Weapons ----
  'weapon:stoeger-longfowler-inspired-shotgun': ['Reported as the Double Barrel Shotgun, based on Stoeger and IGA Longfowler designs, built for close-range stopping power and accepting attachments and tints; the summary cites official screenshots and notes an earlier GTA Online version.'],
  'weapon:850': ['Reported as the Moreland 850, a new pump-action based on the Remington 870, with attachments and tints; the summary cites the Extended Look.'],
  'weapon:bolt-action-sniper': ['Reported as new to the series and based on the Remington 700 BDL, with a manual bolt that sets it apart from semi-automatic marksman rifles; attachments and tints supported.'],
  'weapon:hunter-sniper': ['Reported as a Shrewsbury rifle based on the Accuracy International L96A1, with a 10-round magazine, attachments and tints; the summary cites the 2022 development footage.'],
  'weapon:ruger-10-22-inspired-rifle': ['Reported as a lighter scoped option than the dedicated sniper rifles, with attachments and tints; the summary cites official screenshots.'],
  'weapon:springfield-armory-m1a-inspired-rifle': ['Reported as a semi-automatic precision rifle with a battle-rifle profile, set up for longer range, with attachments and tints.'],
  'weapon:grenade-launcher': ['Reported as a Shrewsbury launcher modelled on the Milkor MGL revolving design, holding ten rounds, with attachments and tints; the summary cites Trailer 2.'],
  'weapon:rocket-launcher': ['Reported as a Shrewsbury RPG modelled on the RPG-7, one rocket at a time, for armour, vehicles and groups; tints only, no attachments. The summary cites the 2022 development footage.'],
  'weapon:fire-bottle': ['Listed separately from the Molotov, which suggests more than one incendiary throwable; it cannot be customised and its behaviour is unknown.'],
  'weapon:flashbangs': ['Described as a less-lethal tactical throwable rather than a fragmentation explosive; effects and duration are not detailed, and it cannot be customised.'],
  'weapon:golf-balls': ['Filed in the throwable inventory with a capacity of one; a similar throwable golf ball existed in GTA V.'],
  'weapon:grenades': ['Modelled on the M61 fragmentation grenade; weapon data from the 2022 footage lists a maximum of 25.'],
  'weapon:molotovs': ['Sets its impact area alight for a short time; weapon data from the 2022 footage lists a maximum of 25.'],
  'weapon:smoke-grenades': ['Reported as a Hawk & Little grenade modelled on the M18, with a standard capacity of 25 and an extended capacity of 30.'],
  'weapon:speargun': [
    'Built for underwater use, firing a spear or harpoon, with its own Spear Ammo category.',
    'Development material links it to a sequence involving a shark; treat that as pre-release information.',
  ],

  // ---- Vehicles: boats ----
  'vehicle:panther-inspired-airboat': ['Called the Airboat or Fanboat; modelled on a Panther airboat and associated with Grassrivers. Reported from Trailer 1; the in-game name is unconfirmed.'],
  'vehicle:airboat-09': ['Reported as the Airgator Airboat 09, modelled on a Diamondback hunting and fishing airboat; seen in official screenshots.'],
  'vehicle:azimut-85-inspired-yacht': ['A luxury motor yacht reported from Trailer 2; in-game name unknown.'],
  'vehicle:azimut-atlantis-45-inspired-yacht': ['A luxury sport cruiser reported from Trailer 2, smaller and faster than the superyachts; in-game name unknown.'],
  'vehicle:delmar': ['A recreational boat reported from Trailer 1, modelled on the real BTN Delmar.'],
  'vehicle:clarion': ['A long, narrow offshore powerboat drawing on the Cigarette 38 Top Gun and Cigarette 515; reported from Trailer 1.'],
  'vehicle:contender-39st-inspired-boat': ['A large centre-console fishing boat reported from official screenshots; in-game name unknown.'],
  'vehicle:crownline-275-ss-inspired-boat': ['A leisure speedboat reported from Trailer 1; in-game name unknown.'],
  'vehicle:cruise-ship': ['Modelled on Royal Caribbean’s Voyager-class ships; whether it can be controlled is unknown.'],
  'vehicle:dive-boat': ['Reported as drawing on the Crusader Boats GFY and Newton 36 Dive Special, a work and diving vessel; seen in Trailer 1.'],
  'vehicle:dinghy': ['Reported as the returning Nagasaki Dinghy, a rigid-hulled inflatable, seen in Trailer 2.'],
  'vehicle:fishing-boat': ['Modelled on the Steiger Craft 31 Miami; tied to the fishing activity. In-game name unknown.'],
  'vehicle:frauscher-1017-gt-inspired-boat': ['A luxury performance boat reported from Trailer 1; in-game name unknown.'],
  'vehicle:horizon-pc60-inspired-yacht': ['A twin-hull luxury power catamaran reported from Trailer 1; in-game name unknown.'],
  'vehicle:crest-kayak': ['Drawing on Crescent Kayak’s Splashback, Ultralite and Primo; engine-free, for quiet lakes, rivers and wetlands.'],
  'vehicle:l35p': ['Reported as the Lure Predator L35P, a centre-console boat drawing on the Contender 25T and 24S; the Predator family also includes the S23 and a police version.'],
  'vehicle:l35p-police': ['Reported as the Lure Predator L35P Police Boat, the law-enforcement version of the civilian L35P, based on the Contender 25T and 24S; seen in official screenshots.'],
  'vehicle:l-rssen-73m-coral-ocean-inspired-yacht': ['Modelled on a 73-metre superyacht, one of the largest yachts identified; reported from Trailer 1.'],
  'vehicle:marquis': ['Reported as the returning Dinka Marquis sailing yacht from GTA V, drawing on Adjutor Yachts; seen in Trailer 2.'],
  'vehicle:rb-s-ii-inspired-coast-guard-boat': ['Modelled on the second-generation Response Boat-Small; a first-generation version is recorded separately.'],
  'vehicle:riva-86-domino-inspired-yacht': ['A large, sleek luxury yacht reported from Trailer 1; in-game name unknown.'],
  'vehicle:s23': ['Reported as the Lure Predator S23, the smaller Predator, based on the Contender 25 Bay, for shallow water and fishing.'],
  'vehicle:sea-ray-350-sundancer-inspired-boat': ['A cabin cruiser for longer coastal trips, reported from Trailer 1.'],
  'vehicle:sea-doo-rxt-x-300-inspired-boat': ['A high-performance jet ski reported from Trailer 1; in-game name unknown.'],
  'vehicle:seashark': ['Reported as the returning Speedophile Seashark: two seats, 400 kg, based on the Sea-Doo RXT, with roots in the Jet Ski of GTA Vice City Stories; seen in Trailer 2.'],
  'vehicle:shipyard-de-hoop-brion-inspired-barge': ['A large working vessel reported from official screenshots; its gameplay role is unknown.'],
  'vehicle:skater-388-inspired-boat': ['A lightweight racing catamaran reported from Trailer 1, among the fastest civilian boats identified.'],
  'vehicle:shitzu-squalo': ['Modelled on the Chris-Craft Stinger 390X. The Ultimate Edition version has a pink-and-blue gradient, is docked at Washington Beach and carries a crate of explosives.'],
  'vehicle:squalo': ['The summary treats the Squalo as a returning Shitzu speedboat based on the Chris-Craft Stinger 390X.'],
  'vehicle:water-taxi': ['Said to link coastal districts, islands and waterfront communities where roads are less convenient; manufacturer and inspiration unknown.'],

  // ---- Vehicles: commercial ----
  'vehicle:benson': ['Reported as the returning Vapid Benson: International 4700 box-truck chassis, two seats, about 7,000 kg, all-wheel drive, five gears; seen in the Extended Look. Earlier games: Vice City, Vice City Stories, San Andreas, GTA IV and GTA V.'],
  'vehicle:biff': ['Reported as the returning HVY Biff, based on the Kenworth T800: two seats, about 9,000 kg, rear-wheel drive; people can stand on it. Seen in the Extended Look; earlier in GTA IV and GTA V.'],
  'vehicle:gmc-topkick-inspired-truck': ['Also matched to the Chevrolet Kodiak: a two-seat medium-duty truck seen in the Extended Look, with its fictional name and maker unknown.'],
  'vehicle:hauler': ['Reported as the returning JoBuilt Hauler, a semi tractor mixing Freightliner and Kenworth styling: two seats, about 9,000 kg, rear-wheel drive, five gears; seen in official screenshots.'],
  'vehicle:mule': ['Reported as the returning Maibatsu Mule, based on the seventh-generation Mitsubishi Fuso Canter: six seats, about 5,500 kg, rear-wheel drive, five gears; seen in Trailer 1.'],
  'vehicle:packer': ['Reported as the returning MTL Packer, based on the 1994 International 9000/9200: two seats, about 12,000 kg, rear-wheel drive, five gears; seen in Trailer 2.'],
  'vehicle:phantom': ['Reported as the returning JoBuilt Phantom, based on the Peterbilt 359 EXHD: two seats, about 12,000 kg, rear-wheel drive, five gears; seen in Trailer 1.'],
  'vehicle:phantom-custom': ['Reported as the returning JoBuilt Phantom Custom from GTA Online, based on a 1984 GMC General with an aerodynamic sleeper: five seats, about 12,000 kg, rear-wheel drive; seen in official screenshots.'],
  'vehicle:stockade': ['Reported as the returning Brute Stockade armoured truck, based on the International 4700: four seats, about 6,500 kg, bullet-resistant front, sides and rear; people can stand on it. Seen in the Extended Look.'],

  // ---- Vehicles: coupes ----
  'vehicle:buick-reatta-inspired-convertible': ['Filed by the summary under coupes: a two-door late-1980s personal-luxury convertible, new to the series, seen in Trailer 2.'],
  'vehicle:fr36': ['Reported as the returning Fathom FR36 from GTA Online, based on the Infiniti G35 (V35): two seats, about 1,515 kg, rear-wheel drive, five gears, liveries; a tuner and drift car seen in the Extended Look.'],
  'vehicle:lincoln-mark-viii-inspired-coupe': ['A large 1990s personal-luxury coupe, two seats, seen in the Extended Look; in-game name unknown.'],
  'vehicle:mercedes-benz-cle-inspired-convertible': ['The summary identifies the Trailer 2 car as the CLE coupe (A236, two seats) rather than a convertible.'],
  'vehicle:sentinel': ['Reported as the returning Übermacht Sentinel XS, based on the BMW M3 E92: two seats, about 1,400 kg, rear-wheel drive, six gears; seen in Trailer 2. Earlier: Vice City, Vice City Stories, GTA IV, GTA V and GTA Online.'],
  'vehicle:windsor-drop': ['The summary instead identifies an Enus Windsor coupe, based on the Rolls-Royce Wraith — two seats, about 2,800 kg, rear-wheel drive, five gears — seen in Trailer 2, returning from San Andreas, GTA V and GTA Online. It may be the same sighting.'],
  'vehicle:zion': ['Reported as the returning Übermacht Zion, based on the BMW M6 E63: two seats, about 1,400 kg, rear-wheel drive, six gears; seen in official screenshots.'],
  'vehicle:zion-cabrio': ['Reported as the returning soft-top Zion, based on the BMW 6-Series E64 cabriolet, with the same 1,400 kg, rear-wheel drive and six gears; seen in the Extended Look.'],

  // ---- Vehicles: cycles ----
  'vehicle:bmx': ['Reported as the returning BMX for tricks, jumps and street riding: one seat, about 105 kg; seen in official screenshots. Earlier: San Andreas, Vice City Stories and GTA V.'],
  'vehicle:cruiser': ['Reported as the returning GTA V beach cruiser — upright, curved frame, wide bars — suited to Vice Beach and Ocean Beach: one seat, about 120 kg; seen in official screenshots.'],
  'vehicle:electric-scooter': ['Reported as new to the series and modelled on the BIRD One rental e-scooter; electric, one seat, filed under cycles. Seen in the Extended Look.'],
  'vehicle:lombike': ['An electric-assist step-through share bike resembling Miami’s bike-share fleets; one seat, new to the series, seen in official screenshots. The name is a provisional identification.'],
  'vehicle:scorcher': ['Reported as the returning mountain bike, drawing on the Saracen Zen with RockShox Domain 180 mm forks: one seat, about 115 kg, for Mount Kalaga trails and dirt roads. Earlier: San Andreas (as the Mountain Bike) and GTA V.'],

  // ---- Vehicles: emergency ----
  'vehicle:ambulance': ['Reported as the returning Brute Ambulance on a Chevrolet Express 3500 cab-chassis: four seats, about 2,500 kg, all-wheel drive, five gears; seen in the Extended Look.'],
  'vehicle:bison-1800-police': ['Reported as the Bravado Bison 1800 Police, based on the Ram 1500 DT: six seats, about 2,100 kg, all-wheel drive, five gears; seen in official screenshots.'],
  'vehicle:pierce-arrow-xt-inspired-fire-truck': ['Reported as the returning MTL Fire Truck, based on the 2012 Pierce Arrow XT rescue pumper: eight seats, about 7,500 kg, rear-wheel drive, five gears. The summary’s source is August 2026 development material.'],
  'vehicle:vapid-lifeguard-truck': ['The summary identifies it as a lifeguard pickup based on the Ford Explorer Sport Trac, four seats, first seen on the Vice City beachfront in Trailer 1.'],
  'vehicle:buffalo-stx-pursuit': ['Reported as the Bravado Police Buffalo STX Pursuit, based on a 2015 Dodge Charger: four seats, about 1,800 kg, rear-wheel drive, eight gears; seen in Trailer 1. Also in GTA Online.'],
  'vehicle:buzzard-police': ['Reported as the Nagasaki Police Buzzard, based on the MH-6 Little Bird with a Miami-style police livery: four seats, about 3,800 kg, a game-file top speed of 160 km/h; seen in official screenshots.'],
  'vehicle:police-cruiser-buffalo': ['Reported as the returning Bravado Police Cruiser Buffalo, an older Dodge Charger patrol car: four seats, about 1,650 kg, rear-wheel drive, five gears, a game-file top speed of 145 km/h; seen in Trailer 1.'],
  'vehicle:police-cruiser-interceptor': ['Reported as the returning Vapid Police Cruiser Interceptor, based on the Ford Taurus Police Interceptor: four seats, about 1,450 kg, rear-wheel drive, five gears. One unit carries VCPD markings with Port Gellhorn text.'],
  'vehicle:vapid-police-car': ['The summary names it the Vapid Police Cruiser Stanier LE, based on the Ford Crown Victoria: four seats, about 1,400 kg, rear-wheel drive, five gears; seen in Trailer 1. A “Ghost” unmarked variant has its own record.'],
  'vehicle:gauntlet-interceptor': ['Reported as the Bravado Police Gauntlet Interceptor, based on the 2018 Dodge Challenger SRT Demon: two seats, about 2,150 kg, rear-wheel drive, five gears; modifiable only at compatible owned properties. Also in GTA Online.'],
  'vehicle:landstalker-xl-police': ['Reported as the Dundreary Police Landstalker XL, based on the fourth-generation Lincoln Navigator: four seats, about 2,500 kg, all-wheel drive, five gears; seen in the Extended Look.'],
  'vehicle:police-maverick': ['Reported as the returning Buckingham Police Maverick, based on the Eurocopter AS350B: four seats, about 6,500 kg, a game-file top speed of 160 km/h; seen in Trailer 1.'],
  'vehicle:montagne-police': ['Reported as the Vapid Police Montagne, a police version of the Montagne based on the sixth-generation Ford Explorer; four seats, seen in Trailer 1.'],
  'vehicle:police-riot': ['Reported as the returning Brute Police Riot, based on the Lenco BEAR armoured vehicle: eight seats, about 6,500 kg, rear-wheel drive, five gears; seen in Trailer 2.'],
  'vehicle:sovereign-107-police-bike': ['Reported as the Western Sovereign 107, based on the Harley-Davidson Road King FLHP: one seat, about 250 kg, rear-wheel drive, four gears. The summary’s source is August 2026 development material.'],

  // ---- Vehicles: helicopters ----
  'vehicle:buzzard-attack-chopper': ['Reported as the returning Nagasaki Buzzard, an armed light helicopter based on the MD Helicopters AH-6 Little Bird: four seats, about 3,800 kg, five-blade rotor; seen in Trailer 2. Earlier: GTA V and GTA Online.'],
  'vehicle:maverick': ['Reported as the returning Buckingham Maverick, a civilian helicopter based on the Bell 206L LongRanger: four seats, about 6,500 kg; seen in official screenshots. It has appeared in most 3D and HD Universe games.'],
  'vehicle:sea-sparrow': ['Reported as the returning two-seat Sea Sparrow, drawing on the Sikorsky/Hughes/Schweizer 300 and Aérospatiale Alouette II, about 3,500 kg — the lightest helicopter listed; seen in Trailer 1. Earlier: Vice City, San Andreas, Vice City Stories and GTA Online.'],
  'vehicle:supervolito': ['Reported as the returning Buckingham SuperVolito executive helicopter from GTA Online, based on the Eurocopter EC145: four seats, about 6,500 kg; seen in Trailer 1.'],
  'vehicle:swift': ['Reported as the returning Buckingham Swift, a fast executive helicopter drawing on the AgustaWestland AW109 and Bell 222: four seats, about 6,500 kg; seen in official screenshots. Earlier: The Ballad of Gay Tony, GTA V and GTA Online.'],
  'vehicle:valkyrie': ['Reported as the returning Buckingham Valkyrie from GTA Online, an armed helicopter drawing on the Bell UH-1 family (UH-1Y Venom, Bell 212/412): four seats, about 6,500 kg, rear bullet protection and several variants; seen in the Extended Look.'],

  // ---- Vehicles: industrial ----
  'vehicle:jack-sheepe-excavator': ['Reported as new to the series, a tracked excavator drawing on the Liebherr R954B HD-S and Samsung SE280LC-2; seen in the Extended Look. No statistics have been published.'],
  'vehicle:flatbed': ['Reported as the returning JoBuilt Flatbed, based on the 2004 Freightliner Century Class 112 (model ID flatbed): two seats, about 6,500 kg, all-wheel drive, five gears; people can stand on the deck. Seen in the Extended Look.'],
  'vehicle:mixer-4-axle': ['The summary describes the standard HVY Mixer, based on the Kenworth T800 — two seats, about 6,000 kg, rear-wheel drive, four gears — known only from the September 2022 development footage. This record is the four-axle variant.'],
  'vehicle:rubble': ['Reported as the returning JoBuilt Rubble from GTA V, based on the Peterbilt 359 EXHD: two seats, about 6,500 kg, rear-wheel drive, four gears; seen in Trailer 1.'],
  'vehicle:tipper': ['Reported as the returning six-wheel Brute Tipper from GTA V, based on the Chevrolet Kodiak / GMC TopKick (model ID tiptruck): two seats, about 5,500 kg, rear-wheel drive, four gears; seen in the Extended Look.'],

  // ---- Vehicles: motorcycles ----
  'vehicle:alvino-v1': ['Reported as the Principe Alvino V1, a new fully faired superbike inspired by the Ducati Panigale V2; two seats, seen in official screenshots.'],
  'vehicle:avarus': ['Reported as the returning LCC Avarus chopper from GTA Online: one seat, about 230 kg, rear-wheel drive, five gears; linked to the Final Chapter MC and seen in Trailer 2.'],
  'vehicle:carbon-rs': ['Reported as the returning Nagasaki Carbon RS from GTA V, inspired by the Ducati 1199 and EBR 1190RS: two seats, about 250 kg, rear-wheel drive, five gears; seen in Trailer 1.'],
  'vehicle:double-t': ['Reported as the returning Dinka Double-T, inspired by Honda’s CBR range: two seats, about 200 kg, rear-wheel drive, five gears; seen in Trailer 1. Earlier: GTA IV, GTA V and GTA Online.'],
  'vehicle:enduro': ['Reported as the returning Dinka Enduro dual-sport from GTA Online, drawing on the Honda XL350, XR500 and CB series: two seats, about 220 kg, four gears. An army-livery version waits at Jason’s safehouse in the Ultimate Edition.'],
  'vehicle:faggio': ['Reported as the returning Pegassi Faggio (model ID faggio2), a Vespa-style scooter: two seats, about 100 kg, rear-wheel drive, three gears; seen in the Extended Look. The Faggio Sport has its own record.'],
  'vehicle:lectro': ['Reported as the returning Principe Lectro (model ID lectro), a naked bike drawing on the Ducati Streetfighter S and MV Agusta Brutale S: two seats, about 250 kg, five gears, with a KERS boost that stores energy for a burst of acceleration.'],
  'vehicle:manchez': ['Reported as the returning Maibatsu Manchez dirt bike, inspired by 500cc KTMs: two seats, about 190 kg, rear-wheel drive, five gears; also filed under off-road. Earlier: Liberty City Stories and GTA Online.', 'Also listed in the Off-Road class, where it is described as one of the lightest vehicles at about 190 kg.'],
  'vehicle:nightblade': ['Reported as the returning Western Nightblade, a dark performance cruiser drawing on the Harley-Davidson Night Rod Special and Dyna Street Bob: two seats, about 205 kg, five gears. Earlier: GTA IV and GTA Online.'],
  'vehicle:pomazoom': ['The summary files the Pomazoom under motorcycles: a three-wheel mobility scooter based on the Pride Maxima 3, new to the series, seen in official screenshots.'],
  'vehicle:sanchez': ['Reported as the returning Maibatsu Sanchez, drawing on the Yamaha YZ450F, Kawasaki KX450F and Honda CRF450X: two seats, about 220 kg, four gears; shown around Mount Kalaga and Vice City. It has appeared across most of the series.', 'Also listed in the Off-Road class, for dirt tracks, forest trails, hill climbs, jumps and off-road racing.'],
  'vehicle:sovereign-107': ['The summary lists the civilian Western Sovereign, a Harley-Davidson Road King tourer — one seat, about 250 kg, four gears — linked to the Final Chapter MC; the police Sovereign 107 has its own record.'],
  'vehicle:suzuki-gsx-r1000-inspired-bike': ['A fully faired superbike inspired by the Suzuki GSX-R1000, new to the series; fictional name and maker unknown. Seen in official screenshots.'],
  'vehicle:zombie-chopper': ['Reported as the returning Western Zombie Chopper, drawing on the Harley-Davidson Fat Bob and Iron 883, with mini-ape bars: two seats, about 225 kg, five gears; seen in Trailer 2. Earlier: GTA IV (as the Zombie) and GTA Online.'],
  // Muscle (community summary, September 2026)
  'vehicle:buccaneer': ['Reported weight about 1,600 kg.'],
  'vehicle:buffalo-stx': ['Reported weight about 1,800 kg, with eight gears.'],
  'vehicle:chino': ['Reported weight about 2,300 kg.'],
  'vehicle:deviant': ['Reported as based on the 1972 AMC Javelin and listed as part of the Wyman collection.'],
  'vehicle:dominator': ['Reported weight about 1,600 kg.'],
  'vehicle:dominator-1967': ['Reported as based on the first-generation Ford Mustang.'],
  'vehicle:dominator-asp': ['Reported weight about 1,665 kg.'],
  'vehicle:dominator-gt': ['Reported weight about 1,820 kg, with six gears.'],
  'vehicle:dominator-gtx': ['Reported weight about 1,670 kg.'],
  'vehicle:ganado': ['Reported as the 1970 Ganado, drawing on the Ford Ranchero and Mercury Cougar; linked to Jason and to a Retro Build variant.'],
  'vehicle:gauntlet-classic-custom': ['The summary also lists a stock Gauntlet Classic at about 1,350 kg; the archive has no separate record for it.'],
  'vehicle:gauntlet-hellfire': ['Reported weight about 1,940 kg.'],
  'vehicle:impaler-1980': ['Reported under the name Impaler ’80 (earlier listed as Impaler LX), weight about 1,630 kg.'],
  'vehicle:impaler-sz': ['Reported weight about 1,830 kg.'],
  'vehicle:moonbeam': ['Listed by the summary as a muscle car (the archive files it under vans), weight about 2,400 kg, from 2022 footage.'],
  'vehicle:phoenix': ['Reported weight about 1,700 kg.'],
  'vehicle:ruiner': ['Reported weight about 1,300 kg.'],
  'vehicle:sabre-turbo': ['Reported weight about 1,200 kg.'],
  'vehicle:sirius': ['Reported as based on the 1970 Mercury Cougar and listed as part of the Wyman collection.'],
  'vehicle:slamvan': ['Reported weight about 1,200 kg.'],
  'vehicle:tulip': ['Reported weight about 1,545 kg; linked to Jason.'],
  'vehicle:tulip-m-100': ['Reported weight about 1,400 kg, with three gears.'],
  'vehicle:vigero-zx-convertible': ['Reported weight about 1,890 kg.'],
  // Off-Road (community summary, September 2026)
  'vehicle:bison-900-monster-truck': ['Reported as the Bravado Bison 900 ’95 Monster Truck, a new monster-truck take on a second-generation Dodge Ram pickup: four seats, oversized tyres and extreme ground clearance, from official screenshots. No statistics yet.'],
  'vehicle:blazer': ['Reported as the returning Nagasaki Blazer quad bike, based on the Yamaha YFZ450: one seat, about 600 kg, all-wheel drive, five gears; seen in Trailer 1. Earlier: GTA V, San Andreas and Vice City Stories.'],
  'vehicle:caracara-4x4': ['Reported as based on the second-generation Ford F-150 Raptor: four seats, about 2,480 kg, all-wheel drive, six gears; seen in Trailer 2. Brian Heder is named as an owner.'],
  'vehicle:dominator-buggy': ['The summary lists the Vapid Dominator ’67 Buggy as off-road: a lifted first-generation Mustang with oversized tyres, two seats, from the Ultimate Edition, storable at Paradise Garage in Watson Bay and possibly tied to the Mud Club.'],
  'vehicle:vapid-dominator-buggy-67': ['Reported as an Ultimate Edition vehicle storable at Paradise Garage in Watson Bay (with a weapon locker and stolen-goods storage), aimed at the Mount Kalaga backcountry and possibly tied to the Mud Club.'],
  'vehicle:hellion': ['Reported as the returning Annis Hellion, mixing the Nissan Patrol Safari Y60 and Jeep Cherokee XJ: two seats, about 1,900 kg, all-wheel drive, five gears; seen in Trailer 1.'],
  'vehicle:kamacho': ['Reported as the returning Canis Kamacho, based on the Jeep Crew Chief 715 concept: four seats, about 2,350 kg, all-wheel drive, five gears. Also shown in Ultimate Edition material tied to One-Eyed Willie’s customisation shop.'],
  'vehicle:outlaw': ['Reported as the returning Nagasaki Outlaw side-by-side, based on the Can-Am Maverick X3 Turbo: two seats, about 850 kg, all-wheel drive, three gears; seen in Trailer 1.'],
  'vehicle:rancher': ['Reported as the returning Declasse Rancher, based on older Chevrolet Suburban models: four seats, about 2,400 kg, all-wheel drive, five gears.'],
  'vehicle:rebel': ['Reported as the returning Karin Rebel, based on the Toyota Hilux: two seats, about 2,400 kg, all-wheel drive, five gears.'],
  'vehicle:reclaimer': ['Reported as a new Vapid midsize pickup based on the 2019–2023 Ford Ranger T6, with four seats; seen in Trailer 1. No other statistics yet.'],
  'vehicle:sandking-xl': ['Reported as the returning Vapid Sandking XL, based on Ford Super Duty trucks: four seats, about 2,400 kg, all-wheel drive, six gears; seen in Trailer 1.'],
  'vehicle:swamp-buggy': ['Reported as based on the Palm Beach swamp buggy, with very tall wheels and raised bodywork for mud, marsh and flooded ground, suited to the Grassrivers. Maker and statistics unknown.'],
  'vehicle:terminus': ['Reported as the returning Canis Terminus, based on the Jeep Wrangler Rubicon (JL): four seats, about 2,000 kg, all-wheel drive, six gears.'],
  'vehicle:verus': ['Reported as the returning Dinka Verus utility ATV, based on the Polaris Sportsman MV850 and 570: two seats, about 750 kg, all-wheel drive, five gears.'],
  'vehicle:walton-l35-stock': ['Reported as the Declasse Walton L35, based on the 1991–1993 Chevrolet S-10: two seats, about 1,600 kg, all-wheel drive, five gears; shown around Port Gellhorn.'],
  'vehicle:yosemite-1500': ['Reported as the returning Declasse Yosemite 1500, based on the first-generation Chevrolet Silverado: two seats, about 1,830 kg, all-wheel drive, four gears.'],
  // Planes (community summary, September 2026)
  'vehicle:dodo': ['Reported as the returning Mammoth Dodo floatplane, based on the de Havilland Canada DHC-2 Beaver: four seats, about 2,000 kg; seen in Trailer 1. Its floats let it use water in the Keys, lakes, rivers and islands. Earlier: GTA III, San Andreas and GTA V.'],
  'vehicle:duster': ['Reported as the returning Western Company Duster, an open-cockpit crop-dusting biplane based on the Stearman Model 75: two seats, about 2,000 kg. Earlier: San Andreas (as the Cropduster) and GTA V.'],
  'vehicle:jet': ['Reported as a four-engine wide-body airliner mixing the Boeing 747-400 and 747-8 Intercontinental: about 38,000 kg, listed with two seats in vehicle data; seen in Trailer 2. Earlier: San Andreas (as the AT-400) and GTA V.'],
  'vehicle:luxor': ['Reported as the returning Buckingham Luxor private jet (model ID luxor), based on the Learjet 45: ten seats, about 6,400 kg; seen in An Extended Look. Earlier: GTA V.'],
  'vehicle:mallard': ['Reported as the returning Western Company Mallard aerobatic plane (model ID stunt), based on the Extra EA-300: one seat, about 1,000 kg, with liveries — the lightest aircraft in the class. Known from August 2026 development material. Earlier: GTA V.'],
  'vehicle:mammatus': ['Reported as the returning JoBuilt Mammatus light aircraft, based on the Cessna 172 Skyhawk: four seats, about 2,000 kg. Earlier: GTA V.'],
  'vehicle:nimbus': ['Reported as the returning Buckingham Nimbus executive jet (model ID nimbus), based on the Cessna Citation X: eight seats, about 6,500 kg; seen in Trailer 1. Earlier: GTA Online.'],
  'vehicle:shamal': ['Reported as the returning Buckingham Shamal business jet, based on the Learjet 45: ten seats, about 6,400 kg. Earlier: San Andreas and GTA V.'],
  // Sedans (community summary, September 2026)
  'vehicle:asterope-gz': ['Reported as the returning Karin Asterope GZ, based on the Toyota Camry XV30: four seats, about 1,500 kg, rear-wheel drive, five gears; linked to the tuner scene. Earlier: GTA Online.'],
  'vehicle:obey-saloon': ['May correspond to the unnamed sedan the summary bases on the second-generation Audi A7 / RS7 four-door fastback (Trailer 1); Obey is the series’ Audi analogue. Not confirmed.'],
  'vehicle:willard-sedan': ['May correspond to one of two unnamed Willard-style sedans the summary lists: a sixth-generation Buick Regal (Trailer 1) or a sixth-generation Buick Skylark (Trailer 2). Not confirmed.'],
  'vehicle:willard-compact-sedan': ['May correspond to one of two unnamed sedans the summary lists: a sixth-generation Buick Regal (Trailer 1) or a sixth-generation Buick Skylark (Trailer 2). Not confirmed.'],
  'vehicle:declasse-sedan': ['May correspond to the unnamed four-seat sedan the summary bases on the tenth-generation Chevrolet Impala (Trailer 1); Declasse is the series’ Chevrolet analogue. Not confirmed.'],
  'vehicle:schyster-station-wagon': ['May correspond to the unnamed wood-panelled wagon the summary bases on the 1986–1988 Chrysler LeBaron Town & Country (An Extended Look), which it files under sedans. Not confirmed.'],
  'vehicle:chrysler-sebring-inspired-sedan': ['Reported as mixing the second-generation Chrysler Sebring and Dodge Stratus, an inexpensive early-2000s midsize sedan; in-game name unknown.'],
  'vehicle:df8-90': ['Reported as the returning Imponte DF8-90 from GTA IV, mixing the Pontiac G6, Grand Am and Sunfire with Honda and Subaru touches: four seats, about 1,700 kg, rear-wheel drive, five gears. Known from September 2022 development footage.'],
  'vehicle:emperor': ['Reported as the returning Albany Emperor, based on the Cadillac Fleetwood: four seats, about 1,900 kg, rear-wheel drive, five gears.'],
  'vehicle:feroci': ['Reported as based on the first-generation Lexus GS 300: four seats, about 1,600 kg, rear-wheel drive, five gears; seen in An Extended Look. Earlier: GTA IV.'],
  'vehicle:vapid-sedan': ['May correspond to the unnamed sedan the summary bases on the Ford Taurus (An Extended Look), the civilian counterpart of the Taurus-style police interceptor. Not confirmed.'],
  'vehicle:dinka-sedan': ['May correspond to the unnamed sedan the summary bases on the tenth-generation Honda Accord (official screenshots); Dinka is the series’ Honda analogue. Not confirmed.'],
  'vehicle:ingot': ['Reported as the returning Vulcar Ingot wagon, mixing the Volkswagen Passat wagon and Nissan Stagea; from September 2022 development footage. Earlier: GTA IV and GTA V.'],
  'vehicle:intruder': ['Reported as the returning Karin Intruder, based on the Infiniti Q45 and I30: four seats, about 1,600 kg, rear-wheel drive, five gears; seen in Trailer 1. Earlier: San Andreas, GTA IV and GTA V.'],
  'vehicle:pmp-700': ['Reported as the Schyster PMP 700, successor to GTA IV’s PMP 600, based on the second-generation Chrysler 300 (LD): four seats, about 1,700 kg, rear-wheel drive, game-file top speed about 140 km/h (87 mph).'],
  'vehicle:primo': ['Reported as the returning Albany Primo, based on the late-1980s Pontiac Bonneville: four seats, about 1,800 kg, rear-wheel drive, five gears; seen in Trailer 1. Earlier: San Andreas, GTA IV and GTA V.'],
  'vehicle:regina': ['Reported as the returning Dundreary Regina wagon, based on the Chevrolet Caprice wagon: four seats, about 1,900 kg, rear-wheel drive, four gears; from September 2022 development footage.'],
  'vehicle:schafter-v12': ['Listed by the summary as a sedan (the archive files it under sports): based on the Brabus E V12, four seats, about 1,500 kg, rear-wheel drive, six gears; seen in Trailer 1. Earlier: GTA Online.'],
  'vehicle:stanier': ['Reported as based on the Ford Crown Victoria: four seats, about 1,800 kg, rear-wheel drive, five gears; the same platform underpins the police Stanier LE, the Ghost Stanier LE and taxi versions.'],
  'vehicle:stanier-1955': ['Reported as the Vapid Stanier ’55, based on the 1956 Ford Fairlane Club Sedan: two seats, about 1,900 kg, rear-wheel drive, five gears; part of the Vintage Vice City Pack. A yellow-and-white one outside the Ocean View Hotel on Shore Drive echoes the Oldsmobile 88 outside Miami Beach’s Avalon Hotel.'],
  'vehicle:vapid-stanier-55': ['Reported with two seats, about 1,900 kg, rear-wheel drive and five gears; a yellow-and-white one parked outside the Ocean View Hotel on Shore Drive echoes the Oldsmobile 88 outside Miami Beach’s Avalon Hotel. The ’55 Stanier also has a second record.'],
  'vehicle:stratum': ['Reported as the returning Zirconium Stratum wagon, based on the Honda Accord wagon: four seats, about 1,800 kg, all-wheel drive, five gears. Earlier: San Andreas, GTA IV and GTA V.'],
  'vehicle:tailgater': ['Reported as based on the Audi A6: four seats, about 1,400 kg, rear-wheel drive, five gears. Earlier: GTA V.'],
  'vehicle:tailgater-s': ['Reported as based on the Audi RS3 sedan: four seats, about 1,340 kg, rear-wheel drive, six gears. Earlier: GTA Online.'],
  // Service, Sports, Sports Classic, Super, SUVs, Utility, Vans (community summary, September 2026)
  'vehicle:airport-bus': ['Reported in the Service class; seen in An Extended Look.'],
  'vehicle:ge-genesis-inspired-locomotive': ['Reported as based on the GE Genesis locomotive; seen in official screenshots. The summary files it under Service.'],
  'vehicle:new-flyer-xcelsior-inspired-bus': ['Reported as based on the New Flyer Xcelsior; seen in Trailer 1. The summary files it under Service.'],
  'vehicle:dashound': ['Reported as based on the MCI Renaissance E-series coach / Greyhound Lines; seen in Trailer 1.'],
  'vehicle:bravado-minivan-taxi': ['May correspond to the Dodge Grand Caravan Taxi the summary bases on the 2011-2020 Dodge Grand Caravan / 2011-2016 Chrysler Town & Country (official screenshots). Not confirmed.'],
  'vehicle:freight-train': ['Reported as based on EMD locomotives with GE AC4400CW influences; seen in official screenshots. The summary files it under Service.'],
  'vehicle:declasse-granger-taxi': ['Reported as based on the Chevrolet Suburban; seen in An Extended Look.'],
  'vehicle:hitachi-rail-inspired-train': ['Reported as based on the Hitachi Metrorail; seen in Trailer 2. The summary files it under Service.'],
  'vehicle:vcmm-train': ['May correspond to the Metromule the summary bases on the Metromule transit vehicle (Trailer 2). Not confirmed.'],
  'vehicle:burrito-shuttle-bus': ['Reported as based on the 1996-2002 Chevrolet Express; seen in Trailer 2. The summary files it under Service.'],
  'vehicle:vapid-taxi': ['May correspond to the Vapid Stanier Taxi the summary bases on the Ford Crown Victoria (Trailer 1). Not confirmed.'],
  'vehicle:8f-drafter': ['Reported as based on the 2018 Audi RS5 Coupe; seen in official screenshots.'],
  'vehicle:alpha': ['Reported as based on the Cadillac Sixteen / 2013 Cadillac ATS; known from September 2022 development footage.'],
  'vehicle:banshee': ['Reported as based on the Dodge Viper; seen in Trailer 2.'],
  'vehicle:blista-compact': ['Reported as based on the first-generation Honda CRX; seen in official screenshots.'],
  'vehicle:buffalo': ['Reported as based on the Dodge Charger; seen in Trailer 1.'],
  'vehicle:carbonizzare': ['Reported as based on the Aston Martin V12 Zagato / Nissan GT-R / Ferrari influences; seen in Trailer 1.'],
  'vehicle:comet-retro-custom': ['Reported as based on the Rauh-Welt Porsche 911 (930); seen in Trailer 1.'],
  'vehicle:comet-s2-cabrio': ['Reported as based on the Porsche 911 Turbo S Cabriolet; seen in Trailer 1.'],
  'vehicle:coquette': ['Reported as based on the Chevrolet Corvette C7 / 2014 Corvette Stingray; seen in Trailer 2.'],
  'vehicle:coquette-d10': ['Reported as based on the Chevrolet Corvette C8; seen in Trailer 1.'],
  'vehicle:cypher': ['Reported as based on the BMW M2 F87 with M6/M8 influences; seen in Trailer 1.'],
  'vehicle:elegy-retro-custom': ['Reported as based on the Nissan Skyline GT-R; seen in Trailer 1.'],
  'vehicle:futo': ['Reported as based on the Toyota AE86 Levin; seen in Trailer 1.'],
  'vehicle:growler': ['Reported as based on the Porsche 718 Cayman; seen in Trailer 2.'],
  'vehicle:itali-gto': ['Reported as based on the Ferrari 812 Superfast; seen in Trailer 1.'],
  'vehicle:itali-rsx': ['Reported as based on the Ferrari SF90 Stradale; seen in An Extended Look.'],
  'vehicle:jugular': ['Reported as based on the Jaguar XE SV Project 8; seen in Trailer 1.'],
  'vehicle:locust': ['Reported as based on the 2015 Lotus 3-Eleven; known from September 2022 development footage.'],
  'vehicle:neon': ['Reported as based on the Porsche Taycan with 918 Spyder, Panamera and 911 influences; seen in An Extended Look.'],
  'vehicle:paragon-r': ['Reported as based on the 2018 Bentley Continental GT; seen in official screenshots.'],
  'vehicle:penumbra': ['Reported as based on the Mitsubishi Eclipse / Audi TT; seen in Trailer 2.'],
  'vehicle:penumbra-ff': ['Reported as based on the second-generation Mitsubishi Eclipse / Eagle Talon; seen in An Extended Look.'],
  'vehicle:raiden': ['Reported as based on the Tesla Model S; seen in official screenshots.'],
  'vehicle:sugoi': ['Reported as based on the Honda Civic Type R FK8; seen in official screenshots.'],
  'vehicle:sultan': ['Reported as based on the Lexus IS / Mitsubishi Lancer Evo VI / Subaru Impreza; seen in Trailer 1.'],
  'vehicle:v-str': ['Reported as based on the 2019 Cadillac CTS-V; seen in official screenshots.'],
  'vehicle:vectre': ['Reported as based on the Lexus RC F; seen in Trailer 2.'],
  'vehicle:cheetah-1995': ['Reported as based on the Ferrari Testarossa / Ferrari 512 BB; seen in Trailer 1.'],
  'vehicle:infernus-classic': ['Reported as based on the Lamborghini Diablo / Cizeta V16T / Ferrari Testarossa; seen in An Extended Look.'],
  'vehicle:kellison-j4-coupe-experimental-inspired-car': ['Reported as based on the Kellison J4; seen in official screenshots. The summary files it under Sports Classic.'],
  'vehicle:mamba-gt': ['Reported as based on the Shelby Daytona Coupe; seen in official screenshots. The summary files it under Sports Classic.'],
  'vehicle:manana': ['Reported as based on the Buick LeSabre / Cadillac Eldorado; seen in official screenshots.'],
  'vehicle:sentinel-classic': ['Reported as based on the BMW E30 M3; seen in An Extended Look. The summary files it under Sports Classic.'],
  'vehicle:progen-emerus': ['Reported as based on the McLaren Senna; seen in An Extended Look. The summary files it in a Super class, which the archive does not use.'],
  'vehicle:aleutian': ['Reported as based on the fourth-generation Ford Expedition (U553); seen in Trailer 2.'],
  'vehicle:astron': ['Reported as based on the Porsche Macan; seen in Trailer 2.'],
  'vehicle:audi-q7-inspired-suv': ['Reported as based on the second-generation Audi Q7; seen in Trailer 1.'],
  'vehicle:baller-second-generation': ['Reported as based on the Range Rover Evoque / Range Rover Sport; seen in official screenshots.'],
  'vehicle:baller-st-d': ['Reported as based on the fifth-generation Range Rover (L460); seen in official screenshots.'],
  'vehicle:cavalcade-xl': ['Reported as based on the 2023 Cadillac Escalade-V; seen in official screenshots.'],
  'vehicle:contender': ['Reported as based on the Toyota Tundra Devolro Diablo / Ford Raptor / Ford F-150; seen in official screenshots.'],
  'vehicle:bravado-suv': ['May correspond to the Dodge Durango (3rd Gen) the summary bases on the third-generation Dodge Durango (Trailer 2). Not confirmed.'],
  'vehicle:dorado': ['Reported as based on the first-generation Dodge Durango; seen in official screenshots.'],
  'vehicle:dubsta': ['Reported as based on the Mercedes-Benz G-Class; seen in Trailer 1.'],
  'vehicle:vapid-suv-first-generation': ['May correspond to the Ford Explorer (2nd Gen) the summary bases on the second-generation Ford Explorer (Trailer 1). Not confirmed.'],
  'vehicle:granger': ['Reported as based on the Chevrolet Suburban; seen in Trailer 2.'],
  'vehicle:granger-3600lx': ['Reported as based on the 2015-2020 Chevrolet Suburban; seen in Trailer 1.'],
  'vehicle:jubilee': ['Reported as based on the Rolls-Royce Cullinan; seen in Trailer 1.'],
  'vehicle:landstalker-xl': ['Reported as based on the fourth-generation Lincoln Navigator; seen in Trailer 2.'],
  'vehicle:mesa': ['Reported as based on the Jeep Wrangler; seen in official screenshots.'],
  'vehicle:montagne': ['Reported as based on the sixth-generation Ford Explorer; seen in Trailer 2.'],
  'vehicle:novak': ['Reported as based on the Maserati Levante / Alfa Romeo Stelvio; seen in official screenshots.'],
  'vehicle:rebla-gts': ['Reported as based on the fourth-generation BMW X5; seen in An Extended Look.'],
  'vehicle:riata-classic': ['Reported as based on the first-generation Ford Bronco; seen in official screenshots.'],
  'vehicle:toros': ['Reported as based on the Lamborghini Urus / Aventador / Audi Q8 influences; seen in official screenshots.'],
  'vehicle:karin-suv': ['May correspond to the Toyota RAV4 (5th Gen) the summary bases on the fifth-generation Toyota RAV4 (Trailer 2). Not confirmed.'],
  'vehicle:xls': ['Reported as based on the Mercedes GL-Class / BMW X5; seen in An Extended Look.'],
  'vehicle:airtug': ['Reported as based on the Clark CT30; seen in An Extended Look. The summary files it under Utility.'],
  'vehicle:forklift': ['Reported as based on the Yale GLP060VX forklift; seen in official screenshots. The summary files it under Utility.'],
  'vehicle:sadler': ['Reported as based on the first-generation Ford F-250 Super Duty; known from September 2022 development footage. The summary files it under Utility.'],
  'vehicle:vapid-tow-truck': ['Reported as based on the 1980s International Harvester S-Series; seen in Trailer 1. The summary files it under Utility.'],
  'vehicle:utility-truck': ['Reported as based on the International 4700 Series; seen in An Extended Look. The summary files it under Utility.'],
  'vehicle:bison': ['Reported as based on the fourth-generation Dodge Ram Quad Cab; seen in Trailer 2.'],
  'vehicle:bison-1800': ['Reported as based on the Ram 1500 (DT); seen in Trailer 2. The summary files it under Vans.'],
  'vehicle:bison-900': ['Reported as based on the second-generation Dodge Ram; seen in Trailer 1. The summary files it under Vans.'],
  'vehicle:bobcat-xl': ['Reported as based on the fourth-generation Chevrolet C/K; seen in Trailer 1.'],
  'vehicle:boxville': ['Reported as based on the GMC Step Van; seen in official screenshots.'],
  'vehicle:burrito': ['Reported as based on the 1996-2002 Chevrolet Express; seen in Trailer 1.'],
  'vehicle:camper': ['Reported as based on the 1996-2002 Chevrolet Express; known from September 2022 development footage.'],
  'vehicle:chevrolet-silverado-6500hd-inspired-truck': ['Reported as based on the Chevrolet Silverado 6500 HD; seen in An Extended Look. The summary files it under Vans.'],
  'vehicle:bravado-minivan': ['May correspond to the Chrysler Town & Country (5th Gen) the summary bases on the fifth-generation Chrysler Town & Country (Trailer 1). Not confirmed.'],
  'vehicle:dodge-dakota-inspired-pickup': ['Reported as based on the Dodge Dakota Convertible; seen in Trailer 1. The summary files it under Vans.'],
  'vehicle:vapid-cargo-van': ['May correspond to the Ford Econoline (4th Gen) the summary bases on the fourth-generation Ford Econoline (Trailer 2). Not confirmed.'],
  'vehicle:ford-f-series-inspired-pickup': ['Reported as based on the third-generation Ford F-Series; seen in official screenshots. The summary files it under Vans.'],
  'vehicle:vapid-flatbed-truck': ['May correspond to the Ford F-Series Flatbed the summary bases on the sixth-generation Ford F-Series (Trailer 1). Not confirmed.'],
  'vehicle:vapid-passenger-van': ['May correspond to the Ford Transit (4th Gen) the summary bases on the fourth-generation Ford Transit (Trailer 2). Not confirmed.'],
  'vehicle:vapid-cargo-van-second-generation': ['May correspond to the Ford Transit Cargo (4th Gen) the summary bases on the fourth-generation Ford Transit Cargo (Trailer 1). Not confirmed.'],
  'vehicle:canis-pickup-truck': ['May correspond to the Jeep Scrambler (CJ-8) the summary bases on the Jeep Scrambler (CJ-8) (official screenshots). Not confirmed.'],
  'vehicle:journey-ii': ['Reported as based on the 1979-1981 Fleetwood Pace Arrow; seen in official screenshots.'],
  'vehicle:benefactor-van': ['May correspond to the Mercedes-Benz Sprinter (2nd Gen) the summary bases on the second-generation Mercedes-Benz Sprinter (official screenshots). Not confirmed.'],
  'vehicle:minivan': ['Reported as based on the Ford Windstar / Dodge Caravan; known from September 2022 development footage.'],
  'vehicle:moocher': ['Reported as based on the 1985 Fleetwood Southwind; seen in official screenshots.'],
  'vehicle:bison-dually-pickup': ['May correspond to the RAM 3500 the summary bases on the RAM 3500 (Trailer 1). Not confirmed.'],
  'vehicle:rexhall-rose-air': ['Reported as based on the Rexhall Rose Air; seen in An Extended Look.'],
  'vehicle:rumpo-custom': ['Reported as based on the GMC Vandura; known from September 2022 development footage.'],
  'vehicle:speedo': ['Reported as based on the 2003-present Chevrolet Express; seen in Trailer 1.'],
  'vehicle:youga': ['Reported as based on the Dodge Ram Van / Dodge B-Series; known from September 2022 development footage.'],
  'vehicle:youga-classic': ['Reported as based on the second-generation Ford Econoline; seen in Trailer 1.'],

  // ---- Editions and media ----
  'editions:gta-vi': [
    'The Vintage Vice City Pack outfits are described as a pastel linen suit with matching hairstyle for Jason and a red sequin mini dress for Lucia.',
    'The ’95 Grotti Cheetah is said to become available later in the story rather than at the start.',
    'The ’67 Vapid Dominator Buggy is described as a two-seat off-road conversion of a first-generation Ford Mustang-style muscle car.',
  ],
  'media:gallery': [
    'An official preview published by Dazed in August 2026 brought new screenshots and artwork of Bae-Luxe, Roxy, Raul Bautista and Boobie Ike, plus a dedicated GTA VI magazine cover.',
    'The cover art revealed on June 18, 2026 follows the series’ collage format, with Jason and Lucia at the centre and panels of Boobie Ike, motorcycles, police vehicles, helicopters, weapons and Leonida scenery.',
    'The original announcement artwork — a tropical sunset with palms — was issued in desktop 16:9, mobile 9:16 and background formats.',
    'Official material should be kept apart from fan art, leaked footage and unofficial renders; this gallery holds only the former.',
  ],

  // ---- Radio ----
  'radio:v-rock': [
    'Returns from Grand Theft Auto: Vice City and Vice City Stories as the hard rock and heavy metal station.',
    'The summary also assigns Go Insane by Lindsey Buckingham (1984) to it.',
  ],
  'radio:emotion-98-3': [
    'Returns from Grand Theft Auto: Vice City and Vice City Stories; the summary lists it simply as Emotion, a pop station.',
    'Song assigned by the summary: Devil Woman by Cliff Richard (1976).',
  ],
  'radio:worldwide-fm': [
    'Returns from GTA V and GTA Online; the summary describes house, jazz and worldbeat.',
    'Songs assigned by the summary: Smile by Jamiroquai and Don’t Send Me Away by Garfield Fleming (1981).',
  ],
  'radio:la-ola': ['Song assigned by the summary: La Cartera by Orquesta Harlow (1974); its genre has not been given.'],
  'radio:circoloco-records-radio': ['Tied to CircoLoco Records, the label Rockstar formed with the Circoloco club brand, whose releases already played through GTA Online’s Media Player. No songs have been assigned to it.'],
  'radio:radio-on-u': ['The name may nod to the real On-U Sound dub label; that link has not been confirmed.'],
  'radio:kaleidoscope-fm': ['The summary files it as a dance station, where this record lists international music.'],
  'radio:stockyard-fm': ['Also written SFM; described as mixing pop from several eras.'],
  'radio:dirty-south-classics': ['Described as Southern hip-hop, fitting the Florida setting; no songs have been assigned to it.'],

  // ---- Gangs ----
  'faction:final-chapter-mc': [
    'An outlaw motorcycle club across Ambrosia County, identified by black leather and Final Chapter patches; its insignia gives 1982 as the founding year.',
    'Reported vehicles: the Avarus and Sovereign motorcycles. Reported weapon: the Duke Arms Mustang .357, a revolver modelled on the Colt Python.',
    'Styled on real outlaw clubs such as the Bandidos. The full extent of its criminal operations has not been shown.',
  ],
  'faction:ptt-youngins': [
    'A loud, highly visible street gang in Southside, Vice City, with a strong social-media presence.',
    'Its compound of contraband can be raided for special items — the PTT Youngin$ Compound Raid, reported as Ultimate Edition content.',
  ],
  'faction:san4san': [
    'Also written San 4 San or S4S; described as a Haitian street gang in Vice City. Known members: Raymond and Ernesto, who run a drug-production operation.',
    'First glimpsed on an S4S chain worn at a car meet in promotional footage, then in gameplay material involving its members.',
    'May echo the Haitian gang of the original Vice City, but is treated as its own organisation, not a confirmed continuation.',
  ],

  // ---- Map: the state as a whole ----
  'map:leonida': [
    'Leonida is commonly estimated at about 1.7 times the playable size of GTA V. That figure comes from pre-release map reconstructions; Rockstar has published no measurement.',
    'The summary expects the bigger difference to be density: several population centres, large wilderness, islands, waterways and far more interiors than earlier games.',
    'Claims that hundreds of buildings can be entered remain unofficial; no total has been announced.',
    '“Gloriana” on licence plates led to talk of a second playable state. Map information instead shows Gloriana Key, an island near Vice City; a Gloriana state, if it exists, is not shown as explorable.',
    'Liberty City is referenced through Lucia’s family history. Nothing indicates it can be visited.',
    'Reported transport: highways, bridges, airports, seaports, rail, public transport and waterways, with boats most useful in the Keys and the Grassrivers.',
  ],

  // ---- Regions ----
  'region:vice-city': [
    'Placed in Vice-Dale County, modelled on Miami-Dade.',
    'Set in the present day rather than the 1980s of the earlier Vice City, with wealthy waterfront developments beside struggling neighbourhoods.',
  ],
  'region:leonida-keys': [
    'Placed in Mariana County, modelled on the Florida Keys.',
    'Smuggling is described as long-established here, with boats and isolated waterways as natural routes; Jason works for local drug runners before the story begins.',
  ],
  'region:grassrivers': [
    'Placed in Mariana County, modelled on the Everglades: shallow waterways, marsh, mangroves and scattered patches of land.',
    'Built around isolation, with boats the practical way through. Reported wildlife includes alligators, snakes, wading birds, wild boars and aquatic species.',
  ],
  'region:port-gellhorn': [
    'Placed in Kelly County, on Leonida’s western side.',
    'A former tourist town in decline: closed attractions, ageing motels and empty strip malls, with an economy of cheap entertainment, drugs, alcohol and roadside business, and its own police presence.',
  ],
  'region:ambrosia': [
    'Placed in Ambrosia County in the centre of the state; possible inspiration Hendry County.',
    'Farming and heavy industry around the Allied Crystal sugar refinery, the area’s main employer, alongside a local biker gang.',
  ],
  'region:mount-kalaga': [
    'Placed in Lummox County, a name known only from pre-release map information.',
    'Forests, canyons, rivers, dirt roads and off-road trails near the northern border, drawing on northern Florida and Georgia.',
    'Associated with hunting, fishing, kayaking and off-road racing; reported wildlife includes deer, cougars and foxes, and the backcountry hosts isolated communities living far from government.',
  ],

  // ---- Places ----
  'location:little-cuba': ['The summary calls this area Little Havana, the name of the real Miami district; Rockstar’s name for it is Little Cuba.'],
  'location:stockyard': ['Said to draw on Wynwood, Miami’s arts and warehouse district.'],
  'location:leaf-links': ['The name was tied to golf in the earlier Vice City; the role of this version has not been shown.'],
  'location:vice-city-international-airport': ['Described as Vice City’s main airport and one of Leonida’s largest transport landmarks, linked to roads and public transport.'],
  'location:venetian-islands': ['Modelled on Miami’s Venetian Islands.'],
  'location:gloriana-key': [
    'Placed in Vice-Dale County; possible inspiration Virginia Key.',
    'Gloriana licence plates were once read as a second state; the map points to this island instead.',
  ],
  'location:ekanfinaka': ['Referenced since early development material; its final appearance is unknown.'],
  'location:waning-sands': ['Placed in Leonard County, whose name appears on in-game road signs; possible inspiration Aventura or Pembroke Pines.'],
  'location:allied-crystal-refinery': ['Described as Ambrosia’s major employer and its most recognisable industrial landmark.'],
  'location:key-lento': ['Modelled on Key Largo. Jason’s early home, Brian Heder’s waterfront property, is here.'],
  'location:watson-bay': ['Placed in Mariana County; possible inspiration Cedar Key. Home of the Paradise Garage.'],
  'location:capri': ['Placed in Mariana County; possible inspiration Sebring.'],
  'location:yorktown': ['Placed in north-western Lummox County; known from development-related information.'],
  'location:little-haiti': ['The name appeared in Grand Theft Auto: Vice City; this is a new HD Universe version.'],
  'location:south-beach': ['Modelled on Miami’s South Beach.'],
  'location:lake-leonida': ['A large inland lake in the centre of the state, separating and linking several regions.'],

  // ---- World: activities ----
  'world:fishing': [
    'Leonida’s coast, rivers, lakes and wetlands are expected to support a wide range of catchable species.',
    'Reported to work from shorelines, docks and boats, with gear and bait, fresh- and saltwater species, and catch-and-release; compared to Red Dead Redemption 2’s fishing.',
  ],
  'world:hunting': [
    'Hunting has appeared during development; whether it ships as an activity is not confirmed.',
    'Reported around Mount Kalaga National Park as a way to earn money, introduced to Jason by one of his contacts.',
  ],
  'world:gym-and-working-out': [
    'Training at a gym is reported to change body shape and physical condition.',
    'Reported exercises: lat pulldowns, bench presses, treadmills, punching bags and squats. Strength work is said to raise Health and cardio to raise Stamina.',
    'A membership is bought at reception; changing rooms swap in workout clothes, and vending machines sell protein and energy drinks that boost Stamina.',
    'Three exercises are reported to complete a daily workout.',
  ],

  // ---- World: wildlife ----
  'world:alligators': ['Found in and out of the water around swamps, rivers and wetlands, making Grassrivers exploration dangerous.'],
  'world:beavers': ['Expected around rivers, lakes and wooded areas.'],
  'world:boars': ['Live in rural and heavily vegetated areas and may turn aggressive when approached.'],
  'world:bobcats': ['Predators of forests and countryside away from the busiest urban areas.'],
  'world:cats': ['Seen around homes, streets and alleys.'],
  'world:cougars': ['The summary identifies them as Florida panthers, one of Leonida’s larger land predators.'],
  'world:cranes': ['Found around wetlands and shallow waterways.'],
  'world:deer': ['Cautious animals of Mount Kalaga National Park and other wilderness that flee when disturbed.'],
  'world:dogs': [
    'Several breeds are reported, among them chihuahuas, Dobermans, German Shepherds and Rottweilers.',
    'Dogs can reportedly be petted, scolded or given treats bought in stores.',
  ],
  'world:dolphins': ['Groups can be met near the surface when travelling by boat.'],
  'world:ducks': ['Found near lakes, ponds and wetlands.'],
  'world:eels': ['Found underwater around reefs, rocks and submerged structures, including in the Leonida Keys.'],
  'world:flamingos': ['Gather in large groups around shallow wetlands and coasts.'],
  'world:foxes': ['Smaller predators of rural and wilderness areas.'],
  'world:german-shepherds': ['May appear with security or law-enforcement personnel as well as with residents.'],
  'world:herons': ['Seen close to shallow water while hunting for food.'],
  'world:iguanas': ['Green iguanas, reflecting the invasive population of real-world South Florida.'],
  'world:killer-whales': ['The summary files whales under 2022 development material; this record rests on the orca at the opening of the first official trailer.'],
  'world:manatees': ['Live in calm rivers, bays and coastal waters.'],
  'world:pelicans': ['Common around beaches, docks and open water.'],
  'world:raccoons': ['Found in both wilderness and towns, drawn to garbage and other food sources.'],
  'world:sea-turtles': ['Can be met while swimming or diving along the coast.'],
  'world:seagulls': ['Seen above Vice City’s beaches, ports and waterfront.'],
  'world:sharks': ['Live in deeper water and are among the main dangers offshore.'],
  'world:snakes': ['Wetlands, forests and rural areas are expected to host several species.'],
  'world:spoonbills': ['Found around shallow water and marshes.'],
  'world:squirrels': ['Found in parks, forests and residential areas.'],
  'world:double-crested-cormorants': ['The summary lists cormorants among unconfirmed species; this record rests on official coastal imagery.'],
}

// Species profiles from a later community summary that copied another wiki's
// animal pages. Scientific names and sizes are that wiki's identifications,
// reported as given; they are not checked against released footage.
const REPORTED_SPECIES = {
  'world:alligators': ['Given as the American alligator (Alligator mississippiensis), size “massive”; said to lie almost fully hidden under the surface or rest on muddy banks. Also in Red Dead Redemption 2.'],
  'world:beavers': ['Given as Castor canadensis, moderate size; said to build dams and lodges on Mount Kalaga’s streams.'],
  'world:boars': ['Given as Sus scrofa, medium size; said to forage in groups and charge rather than flee when threatened. Also in GTA V and Red Dead Redemption 2.'],
  'world:bobcats': ['Given as Lynx rufus, medium size; said to rely on stealth and avoid people.'],
  'world:cats': ['Given as Felis catus, small; seen from Vice City alleys to Port Gellhorn porches, on rooftops and around dumpsters. Also in GTA V and Red Dead Redemption 2.'],
  'world:chihuahuas': ['Given as Canis lupus familiaris, small; said to be seen with residents in urban and beachfront Vice City, some wearing accessories.'],
  'world:cougars': ['Given as the Florida panther (Puma concolor coryi), large; solitary and hard to spot in dense vegetation. Also in GTA V and Red Dead Redemption 2.'],
  'world:cranes': ['Given as Grus canadensis, large; found in Grassrivers marshes and around Mount Kalaga, and seen flying over wetlands. Also in Red Dead Redemption 2.'],
  'world:deer': ['Given as the white-tailed deer (Odocoileus virginianus), large; seen grazing in clearings and crossing trails. Also in GTA V and Red Dead Redemption 2.'],
  'world:dobermans': ['Medium size; said to guard private properties in Vice City and biker-controlled sites around Ambrosia.'],
  'world:dolphins': ['Given as Tursiops truncatus, medium size; associated with the Keys, surfacing near boats, docks and reefs. Also in GTA V.'],
  'world:ducks': ['Given as the mallard (Anas platyrhynchos), small; found on canals, lakes, wetlands and in Vice City parks. Also in Red Dead Redemption 2.'],
  'world:eels': ['Given as Anguilla rostrata, moderate size; said to hide in rocky crevices, reefs and wrecks around the Keys.'],
  'world:flamingos': ['Given as Phoenicopterus ruber, large; feeding in flocks in Grassrivers’ shallows.'],
  'world:foxes': ['Given as the red fox (Vulpes vulpes), medium size; around Mount Kalaga and woods near Port Gellhorn.'],
  'world:german-shepherds': ['Medium size; said to work with Vice City police and guard private and industrial sites.'],
  'world:iguanas': ['Given as the green iguana (Iguana iguana), moderate size; basking on fences, rooftops and trees in Vice City and the Keys. Also in Red Dead Redemption 2.'],
  'world:herons': ['Given as the great blue heron (Ardea herodias), large; hunting fish and amphibians at the water’s edge in Grassrivers and Mount Kalaga. Also in Red Dead Redemption 2.'],
  'world:manatees': ['Given only at genus level (Trichechus), medium size; grazing on underwater plants in the Keys and Grassrivers.'],
  'world:pelicans': ['Given as the brown pelican (Pelecanus occidentalis), large; near docks and fishing boats in the Keys and Port Gellhorn, diving for fish. Also in Red Dead Redemption 2.'],
  'world:raccoons': ['Given as Procyon lotor, moderate size; around Vice City garbage and alleys, and campsites near Mount Kalaga.'],
  'world:rottweilers': ['Medium size; said to appear with gang members and private guards around Ambrosia and Vice City’s rougher neighbourhoods. Also in GTA V.'],
  'world:sea-turtles': ['Given as the green sea turtle (Chelonia mydas), large; met while swimming or diving around the Keys’ reefs, and near secluded beaches.'],
  'world:seagulls': ['Given as the herring gull (Larus argentatus), moderate size; around Vice City’s beaches and boardwalks, Port Gellhorn and piers across the Keys, drawn to food. Also in GTA V and Red Dead Redemption 2.'],
  'world:sharks': ['Identified as the bull shark (Carcharhinus leucas), size “massive”; a danger in deeper water away from the coast. Also in GTA V.'],
  'world:snakes': ['Identified as the corn snake (Pantherophis guttatus), moderate size; hidden in tall grass and undergrowth in Grassrivers and around Mount Kalaga. Variations may exist.'],
  'world:spoonbills': ['Given as the roseate spoonbill (Platalea ajaja), large; pink like a flamingo but told apart by its flat bill, swept side to side through the shallows of Grassrivers.'],
  'world:squirrels': ['Given as the eastern grey squirrel (Sciurus carolinensis), small; in Vice City parks, woodland and around Mount Kalaga.'],
}

export function reportedFor(kind, slug) {
  const key = `${kind}:${slug}`
  return [...(REPORTED[key] || []), ...(REPORTED_SPECIES[key] || [])]
}

export const REPORTED_KEYS = [...new Set([...Object.keys(REPORTED), ...Object.keys(REPORTED_SPECIES)])]
