/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './lib/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        ink: '#0B0F16',
        raised: '#111722',
        surface2: '#18202D',
        paper: '#F2F4F7',
        dim: '#B0B7C3',
        line: 'rgba(255,255,255,0.22)',
        pink: '#F1A3C3',
        mint: '#65DCCB',
        violet: '#9B83F4',
        warn: '#E6D658',
        danger: '#C92A35',
        border: 'rgba(255,255,255,0.22)',
        input: 'rgba(255,255,255,0.22)',
        ring: '#F1A3C3',
        background: '#0B0F16',
        foreground: '#F5F4F0',
        primary: { DEFAULT: '#F2F4F7', foreground: '#0B0F16' },
        secondary: { DEFAULT: '#18202D', foreground: '#F2F4F7' },
        destructive: { DEFAULT: '#C92A35', foreground: '#F5F4F0' },
        muted: { DEFAULT: '#18202D', foreground: '#B0B7C3' },
        accent: { DEFAULT: '#F1A3C3', foreground: '#0B0F16' },
        popover: { DEFAULT: '#111722', foreground: '#F2F4F7' },
        card: { DEFAULT: '#111722', foreground: '#F2F4F7' },
      },
      fontFamily: {
        cond: ['var(--font-cond)', 'Arial Narrow', 'sans-serif'],
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      borderRadius: { lg: '0.75rem', md: '0.375rem', sm: '0.125rem' },
      letterSpacing: { wide2: '0.08em', wide3: '0.14em' },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
