const puppeteer = require('/home/ubuntu/node_modules/puppeteer')
;(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage()
  await page.setViewport({ width: 1440, height: 900 })
  await page.goto('https://lusorae.pt/database/vehicles', { waitUntil: 'networkidle2' })
  await page.click('.wiki-explore-trigger')
  await new Promise((r) => setTimeout(r, 400))
  console.log('active in panel:', await page.$$eval('#archive-explore-panel a.is-active', (a) => a.map((x) => x.textContent.trim()).join(', ')))
  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true })
  await page.goto('https://lusorae.pt/directory', { waitUntil: 'networkidle2' })
  await page.click('button[aria-haspopup="dialog"]')
  await new Promise((r) => setTimeout(r, 500))
  console.log('clipped labels:', await page.$$eval('[aria-label="All sections"] a span:last-child', (s) => s.filter((x) => x.scrollHeight > x.clientHeight + 1).length))
  await page.screenshot({ path: '/home/ubuntu/.claude/jobs/aa302669/tmp/sheet-mobile2.png' })
  await browser.close()
})()
