const puppeteer = require('/home/ubuntu/node_modules/puppeteer')
const out = '/home/ubuntu/.claude/jobs/aa302669/tmp'
;(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage()
  await page.setViewport({ width: 1440, height: 900 })
  await page.goto('https://lusorae.pt/database/vehicles', { waitUntil: 'networkidle2' })
  await page.click('.wiki-explore-trigger')
  await new Promise((r) => setTimeout(r, 400))
  const panel = await page.$eval('#archive-explore-panel', (el) => {
    const r = el.getBoundingClientRect()
    return { left: Math.round(r.left), right: Math.round(r.right), width: Math.round(r.width), sections: el.querySelectorAll('section').length, links: el.querySelectorAll('section a').length }
  })
  console.log('explore panel', JSON.stringify(panel))
  await page.screenshot({ path: `${out}/explore.png` })
  await page.goto('https://lusorae.pt/directory', { waitUntil: 'networkidle2' })
  const dir = await page.evaluate(() => ({ cards: document.querySelectorAll('.site-directory-card').length, links: document.querySelectorAll('main a[href^="/"], .site-directory-grid a').length, overflow: document.documentElement.scrollWidth > window.innerWidth }))
  console.log('directory desktop', JSON.stringify(dir))
  await page.screenshot({ path: `${out}/directory.png`, fullPage: false })
  await page.setViewport({ width: 390, height: 844, isMobile: true, hasTouch: true })
  await page.goto('https://lusorae.pt/directory', { waitUntil: 'networkidle2' })
  console.log('directory mobile overflow', await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth))
  await page.screenshot({ path: `${out}/directory-mobile.png` })
  await page.click('button[aria-haspopup="dialog"]')
  await new Promise((r) => setTimeout(r, 500))
  console.log('sheet groups', await page.$$eval('[aria-label="All sections"] .grid', (g) => g.length), 'sheet links', await page.$$eval('[aria-label="All sections"] a', (a) => a.length))
  await page.screenshot({ path: `${out}/sheet-mobile.png` })
  await browser.close()
})().catch((e) => { console.error(e.message); process.exit(1) })
